#server:
#  port: 9676  
#spring:
#  application:
#     name: bookReservation
#  datasource:
#     url: jdbc:mysql://localhost:3306/bookmgmt?createDatabaseIfNotExist=true
#     username: sagari
#     password: sagari
#     driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect	
#book:
#  jwtSecret: 8b8c590c7f174NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RRUs3NllmZHptNVVrNG9RJKNLDF786ydfkls3075b9c2b5b3baac9c75
#  jwtExpiration: 30000000
#        
#        
# 
#     
